[workspace]
members = ["crates/auth_service", "crates/migrations", "crates/shared"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["lubaskinc0de structnull@yandex.ru"]
description = "DreamTeams auth service"
license = "MIT"
