[package]
name = "crudik_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.47.0", features = ["full"] }
tracing-subscriber = "0.3.19"
